// User
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const QUERY_SELF_SUCCESS = 'QUERY_SELF_SUCCESS';

// Missions
export const ADD_MISSION = 'ADD_MISSION';
export const FETCH_MISSIONS_SUCCESS = 'FETCH_MISSIONS_SUCCESS';

// Soldiers
export const FETCH_SOLDIERS_SUCCESS = 'FETCH_SOLDIERS_SUCCESS';
